# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('geolocalizacion', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=6)),
                ('cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Cine')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('clasificacion', models.CharField(choices=[('A', 'Infantil'), ('B', 'Adolecentes'), ('C', 'Adultos')], max_length=3)),
                ('imagen', models.ImageField(upload_to='img_pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Pelicula'),
        ),
    ]
